import React from 'react';

const Disclaimer: React.FC = () => {
    return (
        <footer className="text-center py-10 mt-8">
            <div className="max-w-4xl mx-auto bg-amber-50 border-l-4 border-amber-400 text-amber-800 p-4 rounded-r-lg" role="alert">
                <p className="font-bold">Disclaimer</p>
                <p className="text-sm">
                    The content generated by this tool is for informational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
                </p>
            </div>
        </footer>
    );
};

export default Disclaimer;
