import React from 'react';

const Disclaimer: React.FC = () => {
    return (
        <footer className="py-5 mt-4 bg-body-tertiary">
            <div className="container">
                <div className="alert alert-warning d-flex align-items-center" role="alert">
                    <i className="bi bi-exclamation-triangle-fill flex-shrink-0 me-3 fs-4"></i>
                    <div>
                        <h4 className="alert-heading h6">Disclaimer</h4>
                        <p className="mb-0 small">
                            The content generated by this tool is for informational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
                        </p>
                    </div>
                </div>
            </div>
        </footer>
    );
};

export default Disclaimer;